-- 코드를 작성해주세요
-- 100 이하: LOW
-- 100 초과 1000 이하: MEDIUM
-- 1000 초과: HIGH

SELECT ID,  
       CASE WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
            WHEN SIZE_OF_COLONY > 100 AND SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
            WHEN SIZE_OF_COLONY > 1000 THEN 'HIGH'
       END AS SIZE
FROM ECOLI_DATA
ORDER BY ID;
