-- 코드를 입력하세요

-- 8~10월 전체 대여 횟수가 5회 이상
-- 서브쿼리 안쓰면? 
-- 8~10월 전체 대여 횟수 5회 이상 -> 월별 대여 횟수


SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >= '2022-08-01'
    AND START_DATE < '2022-11-01'
    AND CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE >= '2022-08-01'
            AND START_DATE < '2022-11-01'
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
GROUP BY MONTH(START_DATE), CAR_ID
ORDER BY MONTH ASC, CAR_ID DESC;